### ISSUE TITLE
Story: Add basic experiments table

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#1]
### Tickets

- [x] Add basic design by @yalozhkin 
- [x] DVC <--> Node interface #3 by @rogermparent 
- [x] Rough table implementation #4
- [x] Represent deeper nesting #12
- [x] Background alternation is broken #30  
- [x] Fix design #8 

### Description

VS Code version of this table: https://github.com/iterative/dvc/wiki/Experiments

Instead of focusing on the historical data (the way `viewer.iterative.ai` or `dvc metrics *` and other commands operate) we are going to try to focus this table in the VS Code version on the "development" phase. As I go and do more experiments (w/o doing `git commits`) I want to see the progress.

<img width="925" alt="Screen Shot 2020-09-28 at 12 57 33 PM" src="https://user-images.githubusercontent.com/3659196/94479826-361e4480-018a-11eb-967c-76180236f807.png">

**Steps/features:**

1. Show the table of experiments attached to the current commit

    - Should show status and update of the current, running experiment(s)

2. Add ability to filter/sort/add/remove columns, etc

3. Add basic actions- select an experiment and checkout it   

4. Run experiment. Results should be visible in the table.

### Design

The experiments table [Figma file](https://www.figma.com/file/ntJpfXe26GZhqVVG7rZSoT/VScode-viewer?node-id=0%3A1).

Preview: 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/454947/96895416-0fa3ae80-1495-11eb-9133-ab6888d50287.png">

Please let me know the **use cases** to assemble.
