### ISSUE TITLE
Story: Experiments table improvements

### ISSUE THREAD

**Issue by rogermparent** [iterative/vscode-dvc#1054]
- [x] #975 
- [x] Fix graphical bug on right side of workspace row (#1140)
- [x] #1064
- [x] #1142
- [x] #1271
- [x] #950 
- [x] #876 
- [x] #787 
- [x] #1210
- [x] #1265
- [x] #955 
- [x] #1266
- [x] Allow for centered cells to display copy button without shifting content, or remove centered cells.
- [x] Make internal cell order state synchronization (within react-table) more efficient (run on init instead of every drag) (#1191) 
- [x] Spinner background https://github.com/iterative/vscode-dvc/issues/1054#issuecomment-991416708 (#1165)
- [x] Copy button layout https://github.com/iterative/vscode-dvc/issues/1054#issuecomment-991416947 (#1155)
- [x] #1187
- [x] Show metrics before params (see `dvc exp show`, Studio) (#1166)
- [x] Show experiment names next to their hashes like in exp show
- [x] #1267
- [x] #1258 
- [x] #1268
- [x] #1259 
- [x] #1269
- [x] #1270
- [x] #1264
