### ISSUE TITLE
Improve the table of experiments UI

### ISSUE THREAD

**Issue by yalozhkin** [iterative/vscode-dvc#1562]
- [x] Sticky table header https://github.com/iterative/vscode-dvc/issues/1562#issuecomment-1124489098 (After scroll initiated display shadow)
- [x] Sticky experiments column #2017
- [x] Table header text size https://github.com/iterative/vscode-dvc/issues/1562#issuecomment-1114403979
- [x] Sort in the header. Remove line indicators and also the context menu https://github.com/iterative/vscode-dvc/issues/1562#issuecomment-1114402261 #1708 || Use: default state (empty), sort 1 (arrow top), sort 2 (arrow down). Every state is activated by a click.
- [x] Show “...” always on the right side https://github.com/iterative/vscode-dvc/issues/1562#issuecomment-1128058554 
- [x] The exp spinning circle border does not move smoothly https://github.com/iterative/vscode-dvc/issues/1562#issuecomment-1164787467
- [ ] Be able to toggle fixed/scrollable table header with the Command Palette https://github.com/iterative/vscode-dvc/issues/1562#issuecomment-1184432137
- [ ] Be able to toggle fixed/scrollable table header with a UI control in the webview 
- [ ] Show a notification (?) if the user trying to toggle exp and 7 expS are already toggled https://github.com/iterative/vscode-dvc/issues/1562#issuecomment-1164798661
- [ ] Explicitly somehow show the running experiment progress https://github.com/iterative/vscode-dvc/issues/1562#issuecomment-1164808580

> There is currently no way to get discrete progress information out of the CLI. The user can proxy progress by:
a.Being familiar with the experiments they are running (they should be).
b.Having the DVC terminal open which displays the CLI output (this opens by default).

- [ ] Avoid displaying in cell values that are different from the real one  https://github.com/iterative/vscode-dvc/issues/1562#issuecomment-1168103301

> Why would we want to do this? I only need to see part of the value to make a decision unless two are very close and then I can investigate further with the tooltips. I would only need the full number if I was going to publish it.

**Comment by maxagin** [comment]
The spinning circle border moves not smoothly. Feels like there is something wrong with it :) I am adding it to TODO.

https://user-images.githubusercontent.com/98249521/175381519-fbf33c5b-c2ee-4134-ab8b-b29a09caac49.mov

**Comment by maxagin** [comment]
I think we can show a notification if the user trying to toggle a new exp (we have a max 7). Because I kinda thought that this is a bug.

https://user-images.githubusercontent.com/98249521/175383474-d21f3912-e450-4240-b584-fb840fdbc585.mov

**Comment by maxagin** [comment]
Would be helpful somehow to show the running experiments' progress. Every time I run an exp I feel like there is an endless process.

**Comment by maxagin** [comment]
I think the Workspace row also needs to be fixed (like the table header). WDYT?

`All the new comments have been included in the description's TODO`

https://user-images.githubusercontent.com/98249521/175386685-67d7e96f-6326-46c3-8e1a-5c0a2bdda10d.mov

**Comment by mattseddon** [comment]
> The spinning circle border moves not smoothly. Feels like there is something wrong with it :) I am adding it to TODO.
> 
>  Screen.Recording.2022-06-23.at.3.14.24.PM.mov

Matches native spinner (`$loading~spin`):

https://user-images.githubusercontent.com/37993418/175463746-0caef264-3a49-45e9-8ff6-220520156627.mov

See also https://code.visualstudio.com/api/ux-guidelines/status-bar#progress-status-bar-item. This is a pattern that I have seen other successful extensions use.

**Comment by maxagin** [comment]
Find a way to show the user that the displayed in cell value is different from the real one. Accuracy? Does it make sense?

<img width="769" alt="Screen Shot 2022-06-27 at 9 15 11 PM" src="https://user-images.githubusercontent.com/98249521/176066497-62d9e9cd-cd17-4345-a677-9639412c3da0.png">

**Comment by shcheklein** [comment]
> Find a way to show the user that the displayed in cell value is different from the real one. Accuracy? Does it make sense?

Could you clarify?

**Comment by shcheklein** [comment]
> Find a way to show the user that the displayed in cell value is different from the real one. Accuracy? Does it make sense?

It makes sense, but not to any reasonable extent that would justify complicating what we show in the cells.

**Comment by maxagin** [comment]
Can we disable some styles when resizing the columns? and for similar cases: when the user works with something, other info blocks should not be affected. 
!! If we have a Copy button at the cell level, we do not need to be able to select textual content.

https://user-images.githubusercontent.com/98249521/177383836-44d796ab-fe34-4a7e-a785-a3ed8ce44675.mov

**Comment by maxagin** [comment]
The timestamp column needs to be moveable and hideable

Scenario: I want to minimize the table info so I can have more space for plots in split view (table/plots). So I would like to be able to get read of the unwanted columns, by moving or hiding them.

<img width="1555" alt="Screen Shot 2022-07-07 at 1 58 50 PM" src="https://user-images.githubusercontent.com/98249521/177840154-ebc594fb-8837-4a8a-bce4-3a407debb7e1.png">

and

<img width="1521" alt="Screen Shot 2022-07-07 at 2 06 01 PM" src="https://user-images.githubusercontent.com/98249521/177840401-484ef5e8-033f-4b39-90cf-100dda4d21e7.png">

WDYT?

**Comment by mattseddon** [comment]
>  Be able to toggle fixed/scrollable table header with the Command Palette
> Be able to toggle fixed/scrollable table header with a UI control in the webview

What value does this add to the user? IMO we don't need to add this.

> Show a notification (?) if the user trying to toggle exp and 7 expS are already toggled https://github.com/iterative/vscode-dvc/issues/1562#issuecomment-1164798661

Once a user is aware that they can only select 7 this no longer becomes an issue. Following the UX guidelines diagram I would take this path:

![image](https://user-images.githubusercontent.com/37993418/178629687-719c6ac0-d06d-4284-8f14-12e63851e45b.png)

FYI https://code.visualstudio.com/api/ux-guidelines/notifications contains full guidelines on notifications.

> Explicitly somehow show the running experiment progress https://github.com/iterative/vscode-dvc/issues/1562#issuecomment-1164808580

There is currently no way to get discrete progress information out of the CLI. The user can proxy progress by:

1. Being familiar with the experiments they are running (they should be).
2. Having the DVC terminal open which displays the CLI output (this opens by default).

> Avoid displaying in cell values that are different from the real one https://github.com/iterative/vscode-dvc/issues/1562#issuecomment-1168103301

Why would we want to do this? I only need to see part of the value to make a decision unless two are very close and then I can investigate further with the tooltips. I would only need the full number if I was going to publish it.

> At the later stage, we will have to implement ‘Unselect All’ and similar options on top of the table, so we can have an option to work with selected rows.

This is in the context menu now. Do we need another option at the top of the table?

> Show all columns, and rows (whether hidden by default or by manual filtering). https://github.com/iterative/vscode-dvc/issues/1994#issuecomment-1177717853

This should be left as a separate issue IMO.

> Clear the selection with the Esc key - Do we have somewhere documented a list of the supported hotkeys? How the users will know about this option?

This is intuitive for a VS Code user. Esc unselects (it is actually annoying when an extension does not provide this option).

**Comment by maxagin** [comment]
Accuracy of displayed by default cell values #2044

**Comment by maxagin** [comment]
Explicitly show the running experiment progress #2043

**Comment by maxagin** [comment]
Show a notification if the user trying to toggle exp and 7 expS are already toggled #2041
Improvements for sections using the copy button #2040
Context menu improvements #2039
If a column has resized, the hint is showing not in the right place #2037
When applying a star to the exp, some strange styles appear on the sidebar #2036
Select and apply star, appears with a small delay #2035
Disable some styles when resizing the columns #2034
Include the Workspace row into the fixed section along with the table header #2032
Timestamp column improvements #2031

**Comment by maxagin** [comment]
https://github.com/iterative/design/issues/27
