### ISSUE TITLE
Star experiments in table

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#1676]
Description: We want to be able to label/mark a single experiment in the table to be able to find it easter.
Original inspiration - gmail stars.
This task is a part of the bigger story #1720

### User story

Iterating on get started repo recently I got lost quickly with all the combinations. Since the dataset name is the same, size in that case was not signalling to me much, etc. I had "good enough" iterations, but it was impossible to put some label, pin, group, save filter, etc.

### TODO

- [x] Be able to add and remove the mark/s (star) from exp/s
- [x]  Checkpoints can have stars.
- [x]  Select a few checkpoints to remove stars.
- [x] Horizontal scroll. To keep the “stars” section (and exp title?) fixed at the left side
- [x]  If a row with checkpoints is folded, we need a sort of way to show that there are checkpoints with stars hidden
- [ ] quick pick - show quick find a starred experiment and select it in the table
- [ ] quick pick - start / unstar. Possible scenario: show quick find exp + star this exp
- [x] Check how does it impact other panels, quick pick, etc? 

[Figma specs](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/1720-%E2%80%A2-Story%3A-Help-navigate-in-a-lot-of-experiments?node-id=808%3A21347)

**Comment by wolmir** [comment]
@maxagin Regarding this comment, what do you mean by "modify the menu options"?

![Screen Shot 2022-06-20 at 14 34 55](https://user-images.githubusercontent.com/1231848/174653871-0808c19b-7cc6-4358-a301-66beb124f1d2.png)

**Comment by shcheklein** [comment]
@maxagin it means that we'll need checkboxes for nested experiments?

**Comment by shcheklein** [comment]
> for example, include actions with the stars
>  for the checkpoints as there are no actions that can be taken

looks like a contradiction? Or I'm missing something ...

**Comment by maxagin** [comment]
You are right. This is my bad, this is the only action (in the context menu), for now, that can be associated with the stars and yes if we want to remove multiple stars by selecting rows, then the checkboxes will be in every row of the table. Great !

**Comment by maxagin** [comment]
>Check how does it impact other panels, quick pick, etc?

@shcheklein  I do not see how this may impact the quick pick or the sidebar. Am I missing something?
@wolmir any ideas in regards to this?

**Comment by shcheklein** [comment]
Some ideas:

- show stars / or highlight in some other way starred experiments in the table
- quick pick - show quick find a starred experiment and select it in the table
- quick pick - start / unstar - not sure how much it is needed tbh
- ribbon - do we want to also show starts?
- in the existing dropdowns / menus where we can see the list of the experiments - do we want to see stars or not
- filter - show only starred? (overall we need to see if need to have some toggles for this, sorts, etc)

**Comment by wolmir** [comment]
@shcheklein Should  the user be able to star experiments while some of them are running?

Currently we disable the context-menu in this case

**Comment by shcheklein** [comment]
It's fine to keep the menu disabled for simplicity (probably we'll have the remove action available soon though) but it's also fine to allow stars on all the experiments in any state. Again, for simplicity. Unless it creates more problems with implementation.

**Comment by maxagin** [comment]
I have updated the [Figma specs](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/1720-%E2%80%A2-Story%3A-Help-navigate-in-a-lot-of-experiments?node-id=985%3A21580). Also nested stars concept is included (first version). Please share your comments.

**Comment by wolmir** [comment]
@maxagin @shcheklein 
Demo of single experiment selection

https://user-images.githubusercontent.com/1231848/175393280-b71309b5-9f27-4d0f-bbbe-299724081400.mov

**Comment by maxagin** [comment]
Great! Thank you @wolmir . Minor: The colours I have used have better contrast than in the theme you're using. But this is fine for now.

**Comment by maxagin** [comment]
@wolmir  can you show how it looks in different themes? Thanks

**Comment by wolmir** [comment]
@maxagin 

https://user-images.githubusercontent.com/1231848/175395276-d9fb6a81-892c-49f7-9974-3de94fa4e63a.mov


https://user-images.githubusercontent.com/1231848/175395611-b028d2bd-e56b-49db-8acf-07e6e84f2c15.mov

**Comment by maxagin** [comment]
@wolmir I have made some adjustments, basically just changed the icon star. Now it is an empty star, which gives more contrast. The specs are updated. Let me know if you have any questions. Thanks !

<img width="957" alt="Screen Shot 2022-06-23 at 5 45 16 PM" src="https://user-images.githubusercontent.com/98249521/175408031-36843984-7590-4651-b9bf-fa4e54dd4482.png">

**Comment by maxagin** [comment]
@wolmir this is also will be fixed soon.

<img width="773" alt="Screen Shot 2022-06-23 at 5 49 23 PM" src="https://user-images.githubusercontent.com/98249521/175409817-4a61eac5-51d4-48aa-90ae-934dd7338314.png">

**Comment by maxagin** [comment]
@wolmir yeah... but the attachment above is from stars Figma, but never mind I will share soon the fix for the selected row star, which will also have an only empty symbol.

**Comment by maxagin** [comment]
@wolmir here we are. Figma is updated. Thanks

<img width="951" alt="Screen Shot 2022-06-23 at 6 05 39 PM" src="https://user-images.githubusercontent.com/98249521/175423225-84a694ff-17f7-4552-9ad1-a021283aa067.png">

**Comment by maxagin** [comment]
@wolmir the [Figma](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/1720-%E2%80%A2-Story%3A-Help-navigate-in-a-lot-of-experiments?node-id=1004%3A18606) was fully updated.

**Comment by maxagin** [comment]
@wolmir have you had a chance to work on the nested stars? Stars for the checkpoints?

**Comment by wolmir** [comment]
I worked on them, yes

**Comment by wolmir** [comment]
@maxagin @shcheklein Demo with ctx-menu options:

@maxagin I'm using the old stars icon, but I'll update it

https://user-images.githubusercontent.com/1231848/175833711-7cf68ebc-d4ef-47b6-bcbe-b0a4bfac6718.mov

**Comment by wolmir** [comment]
First PR for this story is up

**Comment by shcheklein** [comment]
@wolmir @maxagin anything else left here? move to smaller tickets?

**Comment by maxagin** [comment]
@wolmir do you want to create a ticket for those two that are left so we could close this one?

- [ ] quick pick - show quick find a starred experiment and select it in the table
- [ ] quick pick - start / unstar. Possible scenario: show quick find exp + star this exp

**Comment by maxagin** [comment]
@wolmir just  a reminder if you missed the message above:

> @wolmir do you want to create a ticket for those two that are left so we could close this one?

 quick pick - show quick find a starred experiment and select it in the table
 quick pick - start / unstar. Possible scenario: show quick find exp + star this exp

**Comment by wolmir** [comment]
Thanks @maxagin !

Created the new issue here: https://github.com/iterative/vscode-dvc/issues/2106
