### ISSUE TITLE
Story:  Help navigate in a lot of experiments

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#1720]
These comments are the only meaningful thing left in this ticket

![image](https://user-images.githubusercontent.com/37993418/223578217-a1de5a87-2945-42f1-a57b-84128e583e64.png)

----

outdated:

This epic is created so we can discuss the concepts together with the DVC team.

### Ideas

- [x] Star experiments in table #1676
- [ ] Pin experiments to show them at the top (won't do)
- [ ] Be able to drag and drop rows pinned expS (won't do)
- [ ] Naming/renaming experiments after execution (won't do)
- [ ] Able to add context to an experiment (labels https://github.com/iterative/vscode-dvc/issues/1720#issuecomment-1174473366, custom labels, pin, group, comments, free text, notes about experiments etc) (won't do)
- [x] Collapse exps and checkpoints #2071 & Show a limited amount of checkpoints that can optionally be expanded further #1269

### Figma specs

- [Star experiments in table](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/Experiments?node-id=1004%3A18606)
- [Label experiments in the table](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/Experiments?node-id=1075%3A20307)
- [Collapse exps and checkpoints](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/Experiments?node-id=1230%3A36058)
- [Group interesting runs in sections with a title](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/Experiments?node-id=1232%3A40813)
- [Able to add context to an experiment (comments)](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/Experiments?node-id=1227%3A40148)

**Comment by maxagin** [comment]
Labels (using GH colour scheme), just so we can keep this ticket alive. Would probably make sense to sort by label, the same way we are planning to show only starred expS.

<img width="1586" alt="Screen Shot 2022-07-04 at 8 19 01 PM" src="https://user-images.githubusercontent.com/98249521/177227927-7b2a19e8-866a-4f9b-8d1b-6bed6b19b85d.png">

**Comment by maxagin** [comment]
Hey @shcheklein . As a part of the task "Help navigate in a lot of experiments" I think that being able to fold not interesting EXPs can be useful. Please let me know WDYT. 
[Concept on Figma](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/Experiments-table?node-id=1230%3A36058)

**Comment by maxagin** [comment]
@shcheklein here is another concept I would like to share in relation to this ticket: "Group interesting runs in sections with the title"
[Figma](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/Experiments-table?node-id=1232%3A40813)

**Comment by maxagin** [comment]
@mattseddon What do we need to unlock this: Naming/renaming experiments after execution?

**Comment by mattseddon** [comment]
> @mattseddon What do we need to unlock this: Naming/renaming experiments after execution?

I believe the ticket for that is https://github.com/iterative/vscode-dvc/issues/2055

IMO this ticket needs user input and product decisions. 

Hard to know what the next steps are from the OP.

**Comment by maxagin** [comment]
> @mattseddon What do we need to unlock this: Naming/renaming experiments after execution?

>> I believe the ticket for that is https://github.com/iterative/vscode-dvc/issues/2055

Yeah. My question was: How to unlock it? 
From #2055 "I think it's not very hard to implement, but still need some time to finish it."

**Comment by mattseddon** [comment]
> Yeah. My question was: How to unlock it?

First, we need to decide how high of a priority this is for us. We then need to convey that priority to the DVC team so that they can schedule the work... or not.

**Comment by shcheklein** [comment]
Let's keep it and get back when we have a bit more user input + we are done with the current activities. I'd like to keep it lightweight as much as possible. It would be a mistake to implement something complicated like labels. On the other hand, we naming + some lightweight notes/comments could be done I think. Anyways, let's not prioritize for now.

**Comment by dberenbaum** [comment]
My feedback on the experiments table:

- It's not clear which experiments and commits are being shown (or even the relationship between experiments and commits). TBH I'm not sure what's being shown here now so don't know what to suggest 🤔 .
- Sorting and filtering across commits would be helpful (also true for CLI). It's not clear why certain experiments get sorted/filtered and others do not, and it's not helpful to only be able to sort within a commit. Maybe it makes sense to be able to toggle between a Git history view like we have now and more of a flat table view that treats all experiment runs/commits equally?
- Commits without any metrics should probably be hidden/deemphasized.
- What about using the `exp show` options for filtering the rows to show? It would be more consistent across interfaces and increase flexibility.

**Comment by dberenbaum** [comment]
Also this is mentioned in #2726, but I would find renaming (as suggested above) helpful. If it's decided it's worth pursuing, we can look into it on the DVC side.

**Comment by alex000kim** [comment]
Modifying the table view to only show differences (vs all available parameters) would help navigate a table with lots of experiments.

**Comment by mattseddon** [comment]
Closing in favour #1994
