### ISSUE TITLE
Placeholder: Needs design

### ISSUE THREAD

**Issue by mattseddon** [iterative/vscode-dvc#175]
From the VS Code planning meeting on March 17 (AEDT):

This issue is designed to be a collection point for all of the problems that encounter that will need design input.

The idea is that this should help us to communicate asynchronously with @yalozhkin.

@rogermparent please drop anything that you come across in here. 

@yalozhkin let me know what you'd like to see in here.

Thanks!

----------

- [x] Designing with the idea of user-configurable fonts in mind could prove difficult, but I believe the advantages would be worth it https://github.com/iterative/vscode-dvc/issues/175#issuecomment-801416052
- [x] Layout - how do we open the panel initially - https://github.com/iterative/vscode-dvc/issues/175#issuecomment-801532959
- [x] Icon for the extension's tabs (Plots and Experiments webviews)
- [x] User onboarding https://github.com/iterative/vscode-dvc/issues/175#issuecomment-833238457
- [x] Error handling and debugging #470
- [x] Replicate the design for light themes https://github.com/iterative/vscode-dvc/issues/175#issuecomment-876951701
- [x] How do we display experiment errors https://github.com/iterative/vscode-dvc/issues/175#issuecomment-883799520
- [x] We can only display a single icon against an item in a tree view. How would we like to display experiments in the runs view https://github.com/iterative/vscode-dvc/issues/175#issuecomment-885405542.
- [x] Webview empty state https://github.com/iterative/vscode-dvc/issues/175#issuecomment-961526540
- [x] https://github.com/iterative/vscode-dvc/issues/1117
- [x] Plots grid (#1254)
- [x] Checkout https://github.com/microsoft/vscode-webview-ui-toolkit (https://github.com/iterative/vscode-dvc/issues/175#issuecomment-1077043943)
- [x] User flow for #1531
