### ISSUE TITLE
Reconsider column names truncation rules and default width settings

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#1786]
We got into a few problems recently with the latest @iesahin 's attempt to make the PyTorch Lighting project:

<img width="1008" alt="Screen Shot 2022-05-26 at 18 11 44" src="https://user-images.githubusercontent.com/3659196/170803069-b64d4f74-d44f-445b-bbed-5d239cffe350.png">

In this case there are many columns that have names that are hard to distinguish: `...epoch` and `...step`.

The convention to truncate names from the left comes from Studio (intuition that there is more entropy to the right). Clearly in this case (and this is a very popular DL framework) this rule is broken. 

@dberenbaum's comment:

> So here are the metric names in the order I see them: `step`:   `train_acc_step`   `epoch`:   `val_acc_step`   `val_acc_epoch`   `train_acc_epoch`. Now that I look at them, they seem appropriately named as is, and hiding common parts seems like it would be counterproductive (I think they are each as brief as they can be already). To see longer names like this, we may just need to resort to other tricks like tooltips, line wrapping, adjusting font size, etc.

Interestingly enough, in this case even if we truncate from the right, it won't solve the issue (`train_acc`, `val_acc` - repeat).

----

### Todo

- [x] ~@daavoo mentioned that he can take a brief look across some other frameworks.~ I think patterns across ML Frameworks have too many variations.
- [ ] We should take a look at how some other products handle this for the insights - Airtable, W&B, Nepture, Comet, etc. @maxagin can you take this please and share some screenshots?
- [ ] Check that we have tooltips
- [ ] Try different options - two lines? font size?
- [ ] Research default appearance for the table columns (...value ?)
- [ ] To create different examples, trying to find the most suitable approach
- [ ] Look at shorter solutions instead of ‘...’
- [ ] Get info about similar cases from DVC

Any other ideas?
