### ISSUE TITLE
Improvements for sections with the copy button 

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2040]
### TODO

- [ ] Instead of showing a copy button beside the value let’s put it in the tooltip along with the full value
- [ ] Disable the value select option in all cells
- [ ] Add the "Copy value" to the context menu

**Comment by maxagin** [comment]
The title="Copy cell contents" overlaps with the tooltip. A possible solution, display this kind of tooltip on top of the value. 
Won't need to be done if the Copy button will be moved inside the tooltip.

<img width="316" alt="Screen Shot 2022-07-14 at 8 44 50 PM" src="https://user-images.githubusercontent.com/98249521/179149363-9ff518ba-8ae3-4696-865e-c91a132a161f.png">

**Comment by shcheklein** [comment]
>  Instead of showing a copy button beside the value let’s put it in the tooltip along with the full value

We can't I think, or we would have to make the delay 0, or show them on click on the cell.

> Make these tooltips interactable on hover

this is done, I think?

>  Disable the value select option in all cells that have copy buttons

Seems super minor, any specific concerns about this?

**Comment by shcheklein** [comment]
> Hover with delay 0 or 0.5. This is something we better do for any tooltips I think!

No, we can't I think. It will become extremely reactive (imagine tips floating after your mouse pointer)

> Yes

let's remove the checkbox?

> It is minor, but still an improvement I think. When you move the mouse (table view), which changes the appearance of the cursor all the time, it is annoying

Looks like I misunderstood what you actually suggest then. Could you clarify please?

**Comment by rogermparent** [comment]
I can see the existing copy button being considered clunky, but that doesn't necessarily mean the tooltip is the best place to put the control.

I think adding "Copy Cell" to the webview context menu would be the best solution since we already have that pattern of user action established. It'll involve making the context menu recognize cell as well as row, but I'd bet we're probably going to end up doing it for some feature at some point regardless.

**Comment by shcheklein** [comment]
Yes, right click can be a fine compromise to make all the content less jumpy.

**Comment by maxagin** [comment]
> I can see the existing copy button being considered clunky, but that doesn't necessarily mean the tooltip is the best place to put the button. - @rogermparent 

I would expect the copy button to be placed beside the full value, which is the tooltip.

> I think adding "Copy Cell" to the webview context menu would be a very strong, - @rogermparent 

Great idea - adding the "Copy value" also to the context menu! Thank you. Adding it to the TODO

@shcheklein, the description was updated. Do you think we can move forward with the development?

**Comment by shcheklein** [comment]
A few comments.

- since value can be double clicked now in tooltip button is not need / not high priority
- tooltip should disappear on Esc
- probably we can move it a bit to the right / left so that it's possible to move mouse to a cell down to see it's value. I would expect users to skim through values like this

otherwise it's fine to me

**Comment by maxagin** [comment]
> since value can be double clicked now in tooltip button is not need / not high priority

"double clicked" is good but not obvious, or I am wrong? I would keep the copy button in the tooltip. WDYT?

**Comment by maxagin** [comment]
> probably we can move it a bit to the right / left so that it's possible to move mouse to a cell down to see it's value

I would suggest placing it at the top/right (-40%) corner. WDYT?

**Comment by shcheklein** [comment]
> "double clicked" is good but not obvious, or I am wrong?

dunno, good to check, but double click to select something is very basic, OS level operation

btw, I would still support double click on the cell - do not select text, but copy its full value into buffer

> I would suggest placing it at the top/right (-40%) corner. WDYT?

I don't know tbh, any examples (Airtable, Notion, etc?)

**Comment by maxagin** [comment]
> dunno, good to check, but double click to select something is very basic, OS level operation

Sure, but the fact that I am selecting an unknown number, is confusing me. Not sure.

> I don't know tbh, any examples (Airtable, Notion, etc?)

I do not think we would like to change what we currently have, but just improve. No? 
The behaviour can be very different from platform to platform, for example, airtable 0r google docs, on-click - select the cell, on double click - edit cell' content. The select text option is disabled.

**Comment by shcheklein** [comment]
> Sure, but the fact that I am selecting an unknown number, is confusing me. Not sure.

it's not unknown (yes the value is cut, but that it's not unknown). You are not selecting, you are copying the value in the buffer.

Idea here - the more things that are expected to work (even for some people) would work is better. 

It's quite annoying in any of the interfaces when double click to select is broken (usually would select some extra word, or icon), or click + keep + select (via hover) is broken (no matter how you hover it doesn't select an email), etc. We should be paying attention to these very fundamental micro interactions. And there should be a very strong reason to break them.

In this case. We can't let select the value directly (since it's not an actual value)? Arguably this is correct (still though not 100% clear), but can we at least make double click work (no selection appear but we can blink a tip that actual value now in the buffer).

> I don't know tbh, any examples (Airtable, Notion, etc?)

That question was specifically about which corner to pick and what margin to use (-40, -60, etc).

**Comment by maxagin** [comment]
> In this case. We can't let select the value directly (since it's not an actual value)? Arguably this is correct (still though not 100% clear), but can we at least make double click work (no selection appear but we can blink a tip that actual value now in the buffer).

We will allow double-clicking on the cell value. Then the user will be able to copy the value using a keyboard shortcut or content menu.

> That question was specifically about which corner to pick and what margin to use (-40, -60, etc).

@shcheklein here is an example I had in mind:

<img width="1359" alt="Screen Shot 2022-08-02 at 11 30 14 AM" src="https://user-images.githubusercontent.com/98249521/182413796-0695b388-45a0-4d5b-99c5-80615facfd7c.png">

**Comment by maxagin** [comment]
>I don't know tbh, any examples (Airtable, Notion, etc?)

>>That question was specifically about which corner to pick and what margin to use (-40, -60, etc).

@shcheklein I have read a few articles about the table today and found this example by accident. However, as we have discussed this ticket will be taken care of a bit later.

<img width="561" alt="Screen Shot 2022-08-03 at 11 15 02 PM" src="https://user-images.githubusercontent.com/98249521/182756012-9474887f-1af6-4e8d-b8a2-36e4e1056263.png">

**Comment by shcheklein** [comment]
Closing this as a low priority for now
