### ISSUE TITLE
Review: table styles

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2241]
I have reviewed the EXPs table and would like to share with you some comments.
I will be referring to this [Figma file](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/Experiments?node-id=1631%3A119506 )

## TODO 

- [x] Add tooltips to checkboxes and stars
- [x] Hide the right border of the hovered first cell after the horizontal scroll is activated and the shadow appears 
- [x] Increase the workspace row height
- [x] Take off table header right closing line
- [x] Update on-hover header separator line background color
- [x] Take off the first cell's right border when the cell is sticky
- [x] Selected first cell does not have a shadow when scrolled horizontally 
- [x] Keep checkpoint lines on top of the row border
- [x] Update the view background color
- [x] Inconsistent borders on head cells vs body cells
- [x] Remove sticky section bottom border after the vertical scroll is activated
- [x] Keep the resize icon and the vertical line (resize indicator) visible during column resize
- [x] Header cell resizer bar doesn't always reach the top of a cell
- [x] Remove the EXP name from being a toggle
- [x] When star an experiment the weird progress lines show on the sidebar. (Bug?)

### Hint/Tooltip 

- [ ] Add hint "Add/Remove to plots" (maybe different wording) when the EXP's circle has hovered
- [ ] Hints like Select, Add Star and similar. The text is too big. Try to make it the same as when you hover on the Experiments tab
- [ ] Hints need to be closer to the cursor
- [x] Hints do not need to have a triangle at the top

 
### Row

- [x] Update row selection styles
- [x] A number of hidden element indicators (circle with the number) styles for rested and selected row states
- [x] There is a little spacing between the elements in the design, for example, checkbox and star, it is important to show the user where the active area ends and where the new starts
- [x] Chevron on hover - cursor pointer
- [x] The table's last row does not need a button border
- [x] Checkbox and star styles when the row selected

### Context menu

- [x] All context menus need to appear on the right side of the target point.
The context menu is usually placed on the right/bottom side of the mouse click unless it is close to the right age of the screen, then it will appear on the left side. However, in VSCode it seems like always on the right side, but we can do it correctly I think.
- [x] Remove the triangle (on top) from the context menus

**Comment by maxagin** [comment]
In relation to the Experiments table: improve styles #2070

**Comment by maxagin** [comment]
Hi @julieg18 . I have added to [Figma](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/Experiments?node-id=1671%3A118298) the new styles "Number of hidden elements indicators" when changing the selection styles this also needs to be corrected. Thank you!

<img width="1054" alt="Screen Shot 2022-08-24 at 1 30 51 PM" src="https://user-images.githubusercontent.com/98249521/186485467-457de51f-9006-4ea8-aa71-c6097177e1e2.png">

**Comment by julieg18** [comment]
Created a task list:

- [ ] Add tooltips to checkboxes and stars
- [ ] Keep the resize icon and the vertical line (resize indicator) visible during column resize
- [ ] Increase the workspace row height
- [ ] Update on-hover header separator line background color
- [ ] Take off table header right closing line
- [ ] Stop sidebar sidebar progress lines when starring a experiment
- [ ] Keep checkpoint lines on top of the row border.
- [ ] Update row selection styles 
- [ ] Add hover styles to header cells
- [ ] "Number of hidden element indicators"


> When the header section/s is on hover, hover styles need to be applied (see Figma).

When you are referring to hover styles, do you mean changing the background color? Wanted to make sure since we took off that particular style on the body cells :)

Also, due to needing to update multiple cells on hover, this may require too much rerendering 🤔 Will do some research before confirming though :)
<img width="625" alt="image" src="https://user-images.githubusercontent.com/43496356/186516691-68055f5c-42b8-42ca-b38f-416ba0a8eb27.png">

> I have added to [Figma](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/Experiments?node-id=1671%3A118298) the new styles "Number of hidden elements indicators" when changing the selection styles this also needs to be corrected. Thank you!

Hmmm, I'm not quite sure what the task is. Could you provide some more context?

**Comment by maxagin** [comment]
>When the header section/s is on hover, hover styles need to be applied (see Figma).

>>When you are referring to hover styles, do you mean changing the background color? Wanted to make sure since we took off that particular style on the body cells :)

Yes. You are right about the fact that we have removed the particular style on the body cells, but for the header, it is different, already because the header cells have the lines. Most importantly we would like to have the same hover style for the header cells as we are using for the row on hover. 

>I have added to [Figma](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/Experiments?node-id=1671%3A118298) the new styles "Number of hidden elements indicators" when changing the selection styles this also needs to be corrected. Thank you!

>>Hmmm, I'm not quite sure what the task is. Could you provide some more context?

I am adding it to the description like this: A number of hidden element indicators (circle with the number) styles for rested and selected row states. Let me know if you have any questions, please.

@julieg18  I have added a few more things to the TODO list and published them in the description (on top).

Question: I do not understand what this is about: Stop sidebar progress lines when starring an experiment?

**Comment by maxagin** [comment]
`Preparing the table for "Text selection in the table's header and body cells" modifications.`

Currently, to show exp in plots you can click on the circle/EXP name. Let's remove the EXP name from being a toggle. In other words, the toggle will be only the circle.

<img width="729" alt="Screen Shot 2022-08-24 at 10 28 27 PM" src="https://user-images.githubusercontent.com/98249521/186561135-50f616a1-efb6-433d-8fd1-5c2ad1aca436.png">

The description was updated. The new task was included.

**Comment by maxagin** [comment]
After the horizontal scroll is activated and the shadow appears, the right border of the hovered first cell does not need to be shown.

<img width="813" alt="Screen Shot 2022-08-25 at 1 04 14 AM" src="https://user-images.githubusercontent.com/98249521/186579646-74719307-6dd5-4eff-9500-409875d2c222.png">

**Comment by julieg18** [comment]
> Question: I do not understand what this is about: Stop sidebar progress lines when starring an experiment?

I was referring to weird sidebar progress bars that you already mentioned (and said were probably already reported): 

<img width="937" alt="image" src="https://user-images.githubusercontent.com/43496356/186660450-38c8ca9a-bbac-4a30-ac5e-8980eaff6f1e.png">

**Comment by maxagin** [comment]
>I was referring to weird sidebar progress bars that you already mentioned (and said were probably already reported):

Yeah @julieg18. Thank you !
The description was updated. The new task was included.

**Comment by julieg18** [comment]
Reviewed the comments made in #2289! Looks like there are currently two unresolved ones:

> Use the full height of the cell (also I have a feeling the blue line has opacity. Right?):
> <img width="797" alt="image" src="https://user-images.githubusercontent.com/43496356/187560061-e5329a64-0a56-4aca-8c36-a494e2fed200.png">

Should be doable and updated the task list!

> Very minor: consistent vertical lines
> <img width="803" alt="image" src="https://user-images.githubusercontent.com/43496356/187560131-8d6f69bb-0c27-4f28-be2a-86672b0a70dc.png">

Don't think this is currently doable without creating a performance heavy solution :(

**Comment by julieg18** [comment]
> `Preparing the table for "Text selection in the table's header and body cells" modifications.`
> Currently, to show exp in plots you can click on the circle/EXP name. Let's remove the EXP name from being a toggle. In other words, the toggle will be only the circle.

@maxagin, is the goal just to make the text selectable? If so, maybe we should consider making the text selectable but also still clickable. If we make the toggle only the circle, it would be very small and more difficult to click on.

**Comment by maxagin** [comment]
>Preparing the table for "Text selection in the table's header and body cells" modifications.
Currently, to show exp in plots you can click on the circle/EXP name. Let's remove the EXP name from being a toggle. In other words, the toggle will be only the circle.

>>@maxagin, is the goal just to make the text selectable? If so, maybe we should consider making the text selectable but also still clickable. If we make the toggle only the circle, it would be very small and more difficult to click on.

@julieg18, the active area of any clickable icon needs to be 20x20 (we also use 16x16). For example, the checkbox and star active area are 20x20px. The toggle is the icon (circle). IMO if the trigger is cell or name it is confusing.

<img width="751" alt="Screen Shot 2022-08-31 at 9 07 41 PM" src="https://user-images.githubusercontent.com/98249521/187811658-0ed8ee4c-8a46-481f-8494-4719c0a10a2d.png">

**Comment by maxagin** [comment]
> Very minor: consistent vertical lines
> <img width="803" alt="image" src="https://user-images.githubusercontent.com/43496356/187560131-8d6f69bb-0c27-4f28-be2a-86672b0a70dc.png">

>> @julieg18 Don't think this is currently doable without creating a performance heavy solution :( 

I have noticed that some lines are fine some not. Why it's happening?

<img width="465" alt="Screen Shot 2022-08-31 at 9 16 18 PM" src="https://user-images.githubusercontent.com/98249521/187812104-2f8f113e-bd0e-498c-8242-66ff01b48b2d.png">

**Comment by julieg18** [comment]
> I have noticed that some lines are fine some not. Why it's happening?

Due the differences between how the borders are added on the head vs the body. The border on the head cells are adding by applying `border-right` to each cell. Body cells, on the order hand, get their borders on the right and left sides, causing the slight inconsistency between the placement of the borders... 

Actually, now that I type that, I think I have an idea that will fix the lines without javascript... Let me test it out!

**Comment by maxagin** [comment]
After the vertical scroll is activated and the shadow appears, the stuck section bottom border needs to be removed. Same as we do in similar cases. 

<img width="1740" alt="Screen Shot 2022-09-01 at 5 44 00 PM" src="https://user-images.githubusercontent.com/98249521/188025983-9bb49c0e-d5ea-4cf9-a5ce-926e8e1c5c30.png">

The description was updated. The new task was included.

**Comment by maxagin** [comment]
First row under the workspace ideas:
1. There is no point to have a checkbox, star and chevron
2. If the first is correct: we can move everything a little to the left
3. Have it sticky
WDYT @shcheklein ?

**Comment by shcheklein** [comment]
@maxagin it should be a separate discussion? let's finally close this one?

**Comment by maxagin** [comment]
### Shabbos Nocturne

- Chevron on hover - cursor pointer.
- There is a little spacing between the elements in the design, for example, checkbox and star, it is important to show the user where the active area ends and where the new starts. 
- The sort arrow in the header cell does need to have BG on hover but needs to have a cursor (pointer).
- Click on the Sort arrow - the context menu appears - if you hover on the arrow again the tooltip will be shown on top of the context menu. Do not show a tooltip when the menu is opened.
- All context menus need to appear on the right side of the target point.
- Remove the triangle (on top) from the context menus
- Hints like Select, Add Star and similar. The text is too big. Try to make it the same as when you hover on the Experiments tab.
- Hints need to be closer to the cursor.
- Hints do not need to have a triangle at the top.

---

p.s.
Love how height the task list becomes. Would like to see at what point Babylon will fall. @shcheklein, have you ever had a chance to be in a position of a God?


https://user-images.githubusercontent.com/98249521/188222453-f11c2522-023f-40cc-8b46-4cf81d7aa0d1.mp4

---

The description was updated. The new task was included. If Babylon will fall today, we will create a new ticket!

**Comment by maxagin** [comment]
Add tooltip: Add/Remove to plots (may be different wording) when the EXP's circle has hovered.

The description was updated. The new task was included.

**Comment by maxagin** [comment]
The D&D cursor appears when the header block has hovered. Blocks like "Create" have no active space on top. Let's make sure that all the space of the block can be used to D&D, including train.py from the attached example.

<img width="1339" alt="Screen Shot 2022-09-02 at 4 50 55 PM" src="https://user-images.githubusercontent.com/98249521/188233585-f3ed8349-c73b-4cce-bb8a-485313b8ad91.png">

The description was updated. The new task was included.

**Comment by mattseddon** [comment]
> When star an experiment the weird progress lines show on the sidebar. (Bug?)

Was fixed by #2042

**Comment by maxagin** [comment]
@julieg18 please post the links to PRs . I am having a hard time finding it. Thanks

**Comment by maxagin** [comment]
The description was updated. Please take a look.

**Comment by mattseddon** [comment]
Can we move the header updates into #2256?

**Comment by julieg18** [comment]
> @julieg18 please post the links to PRs . I am having a hard time finding it. Thanks

Sure!

### #2289: 
* add tooltips to row actions (checkbox and stars)
* take off first cell right border when the cell is sticky
* increase workspace row height
* take off right border on the head rows last children
* update column resizer hover background color

### #2316:
* keep checkpoint dotted lines above border
* keep head cell and body cell borders lining up correctly
* turn off workspace row border when sticky
* update table container background

### #2305:
* show columnResizer bar active styles on hover and when the column is being resized
* keep the resizer bar the same height of the cell(s)

**Comment by maxagin** [comment]
- The table's last row does not need a button border

The description was updated. The new task was included.

**Comment by julieg18** [comment]
> Checkbox and star styles when the row selected

I can update the star styles (#2351) but the checkbox is different from the star since a vscode component instead of a custom component. We could figure out a way to update it with some JavaScript but I don't think it's necessary. VSCode keeps the checkbox on default styles when you select rows in the tree as well:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/43496356/189008226-c11cea8f-0998-4a90-8bfc-6f71f1c89ca4.png">

**Comment by mattseddon** [comment]
@julieg18 @maxagin I looked at 

> - [ ] All context menus need to appear on the right side of the target point.
The context menu is usually placed on the right/bottom side of the mouse click unless it is close to the right age of the screen, then it will appear on the left side. However, in VSCode it seems like always on the right side, but we can do it correctly I think.

What we have right now is probably the best available with tippy. Take a look at the docs for [placement](https://atomiks.github.io/tippyjs/#placements) if you want to double-check. IMO it would make more sense to wait for #2350 before investing any more effort in trying to improve context menus.

**Comment by maxagin** [comment]
I am not sure it makes sense to have all stars (checked and unchecked) look the same. I think this negates the purpose of this functionality.

<img width="1625" alt="Screen Shot 2022-09-12 at 4 59 14 PM" src="https://user-images.githubusercontent.com/98249521/189758987-70f2efba-5d01-400e-958c-04ad5654b1e3.png">

**Comment by shcheklein** [comment]
> I am not sure it makes sense to have all stars (checked and unchecked) look the same. I think this negates the purpose of this functionality.

Yep, it can be a bit dangerous. Actions itself is fine, but I would expect to have undo for this, or an option to get back.

Otherwise someone from time to time will be clicking by an accident thus removing carefully created state.

**Comment by julieg18** [comment]
> I am not sure it makes sense to have all stars (checked and unchecked) look the same. I think this negates the purpose of this functionality.
> Yep, it can be a bit dangerous. Actions itself is fine, but I would expect to have undo for this, or an option to get back.
> Otherwise someone from time to time will be clicking by an accident thus removing carefully created state.

Are we referring to the color of the star icon? We can adjust the opacity to make an unchecked star partially opaque again, hopefully to the point where it's still viewable across most themes 🤔

**Comment by shcheklein** [comment]
Okay, I might have missed the issue that @maxagin was referring to. I was thinking about mass actions like select experiments - star/unstar, toggle plots. They could be destructive in nature and they are one mistake away (one wrong click) cc @mattseddon .
