### ISSUE TITLE
Story: Experiments workflow

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#239]
## Motivation

Ability to run/stop/resume/queue experiments as reflected by the [`dvc exp`](https://dvc.org/doc/command-reference/exp) is considered one of the key features we'd like to release as part of the initial version. Motivation behind the corresponding DVC functionality can be found in docs or briefly in this [blog](https://dvc.org/blog/dvc-2-0-release).

To play with the experiments online: https://katacoda.com/dvc/courses/get-started/experiments

## Tickets

New tickets and scope might come as we have some initial design input from @yalozhkin .

- [x] Add extension Commands:
    - [x] Stop an experiment(s) https://github.com/iterative/vscode-dvc/issues/230
    - [x] Apply, branch, remove https://github.com/iterative/vscode-dvc/issues/227
    - [x] Queue, run all, gc https://github.com/iterative/vscode-dvc/issues/229
    - [x] `exp run --reset` #304 
    
- [x] Add UI/UX for these actions:
    - [x] Apply, branch, remove ~https://github.com/iterative/vscode-dvc/issues/228~ https://github.com/iterative/vscode-dvc/issues/1267
    - [x] Stop https://github.com/iterative/vscode-dvc/issues/231
    - [x] Reset: https://github.com/iterative/vscode-dvc/issues/233
    
- [x] Checkpoint experiments handling:
    - [x] ~~Detect checkpoint (partial) experiment https://github.com/iterative/vscode-dvc/issues/232~~
    - [x] Reset (UX and command): https://github.com/iterative/vscode-dvc/issues/233
   

## Details

**As we discussed we start the following scope:**

- Run an experiment in the workspace - this is default and it is done to some extent. But might require changes from the design perspective.
- Queue experiments [run](https://dvc.org/doc/command-reference/exp/run) `--queue` and run them all `--run-all`

- an action to `stop` and experiment(s) by sending a `SIGTERM`

- Reset to run from "scratch": [run](https://dvc.org/doc/command-reference/exp/run) `--reset`
- Apply (get) the experiment - [apply](https://dvc.org/doc/command-reference/exp/apply)
- Branch (get as a branch) the experiment - [branch](https://dvc.org/doc/command-reference/exp/branch)
- Remove an experiment(s) - [remove](https://dvc.org/doc/command-reference/exp/remove)

Only after that when we have more clarity, probably after the initial release we can do "remote" commands

- `push`, `pull`, `list`
---
## Design

The running experiments workflow includes:

- The Runs panel with toolbar
- The Experiments table with toolbar

A running experiment preview:
![image](https://user-images.githubusercontent.com/454947/116607208-5d184100-a93a-11eb-8fa8-361896c1aaeb.png)

More details and states in the Figma [spec](https://www.figma.com/file/Vjywcp2UAmvJspfz4ZolaU/%F0%9F%92%BE-DVC-VSCode-Specs-and-Ideas?node-id=5%3A79398).
 
cc @yalozhkin
