### ISSUE TITLE
Improve behaviour of Run Experiment command

### ISSUE THREAD

**Issue by ryanraposo** [iterative/vscode-dvc#27]
- [x] (#33) Add a contextual (right-click) to items in the Explorer view, with a relevant 'WHEN' condition to limit its appearance. 

- [x] (#33) Add a contextual (right-click) to open editors, with a relevant 'WHEN' condition to limit its appearance. 

- [x] (#28) Add a button for this command to the webview. 

- [x] (#35) Comparable commands use Output (read-only) channels, so they are more appropriate here and should be used.

- [ ] The webview should better reflect usage of this command, its progress, and results. Add a mechanism that links the two. 

- [ ] The implementation should better capture the commands optional behaviour. Change it to a menu and include subcommands. 

- [x] Support properly conda, virtualenv, etc- https://github.com/iterative/vscode-dvc/issues/27#issuecomment-752758344
