### ISSUE TITLE
Story: Improve Onboarding

### ISSUE THREAD

**Issue by julieg18** [iterative/vscode-dvc#2793]
We need to make what the product has to offer more clear when it's first installed and help users who don't have a DVC project set up already to get started with experiments/plots.

### Steps

- [x] Improve walkthrough (#2573, #2588)
- [x] #2683
- [x] #2776
- [x] https://github.com/iterative/vscode-dvc/issues/2765
- [x] Look into assisting users with installing DVC. How Jupiter notebooks install packages for users is one example to look into. https://github.com/iterative/vscode-dvc/issues/2829
- [x] Help users get started with their own experiments or plots We could use some kind of template for projects or use the upcoming changes to DVCLive to generate experiments. (See discussion in #2608)
- [x] Review Get Started - https://github.com/iterative/vscode-dvc/issues/2725
- [x] #2947 - setup onboarding for users who do not have project
- [ ] https://github.com/iterative/vscode-dvc/issues/3021
- [ ] Review, including the messaging (e.g. Global - can users understand?, we don't need details like `exp_save`, etc) #3057

**Comment by mattseddon** [comment]
We need to take into consideration the details here: https://github.com/iterative/dvclive-exp-tracking for the way the onboarding flow needs to look. 

I think there need to be two separate options when there is no project:
1. I want to init a new project
2. I want to instrument my code

cc @sroy3

**Comment by shcheklein** [comment]
2 does require 1 though? (it requires `dvc init`)

**Comment by mattseddon** [comment]
I am wrong

**Comment by mattseddon** [comment]
When we detect a user has a global install of the CLI and no project or data we can put a screen in front of the CLI unavailable screen. This screen will look like this:

### No Project

![image](https://user-images.githubusercontent.com/37993418/208808978-a0b1109c-f244-4a1b-8544-74b5fbdb4761.png)

### With Project 

![image](https://user-images.githubusercontent.com/37993418/208808934-f3698e8e-9fa7-4e10-b935-6557504035f4.png)

Both of the buttons with the "secondary appearance" (one of which is highlighted below) will result in onboarding being dismissed for the remainder of the session (or we could have the state for future sessions).

![image](https://user-images.githubusercontent.com/37993418/208809149-ebd6b29f-2380-45a4-ab41-ded2ac1a4359.png)

We also need to add the above Dismiss button + Don't Show Again to the project has no data screen:

![image](https://user-images.githubusercontent.com/37993418/208809445-04fbf650-c8ee-429b-8f5b-f44202edd5fa.png)

When the CLI is installed but behind the current required version we should assume they are not a new user and simply show a screen with the details of the currently selected CLI and ask them to upgrade to continue. Something along the lines of:

<img width="472" alt="image" src="https://user-images.githubusercontent.com/37993418/208810979-9fd528a2-bbc2-4686-8a53-cdca9cb08851.png">

We also need to integrate this new webview with the existing flow/toast messages. Hopefully, the above change will mean we can now remove a lot of the existing messages.

**Comment by mattseddon** [comment]
We also need to consider whether or not we are going to validate the version of Python on the User's system (>= 3.8?) before trying to install DVC and a package.

**Comment by dberenbaum** [comment]
One more small thing on install here: when you choose an environment where dvc cannot be found, the extension silently fails. It would be nice to fail louder and take the user back to the command bar to try a different environment/path.


https://user-images.githubusercontent.com/2308172/209034238-f37296e8-9119-4100-88c1-5fac1072e85f.mov

**Comment by mattseddon** [comment]
@dberenbaum do you have `Do Not Show CLI Unavailable` checked in your settings?:

<img width="1289" alt="image" src="https://user-images.githubusercontent.com/37993418/209037852-b0bf811a-8aa3-4246-aae8-2154d9d8d3ae.png">
