### ISSUE TITLE
Onboarding to running experiments

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#3058]
Most options in the sidebar are about viewing experiments, which doesn't make much sense for a new project without any experiments. It would be good to focus on running experiments as the starting point.

@shcheklein Made the comparison to `launch.json`, and I think we can borrow a lot from VS Code's [debugging setup](https://code.visualstudio.com/docs/editor/debugging). When you first try to run an experiment, we can try to funnel users through a workflow like:

1. Pick the file to run the experiment. If it's not Python, what do we do?
2. Once the file is picked, we can show the instructions to add DVCLive, and maybe we can even validate that DVCLive has been added to the code before allowing users to continue.
3. Once DVCLive is added, users can choose whether to configure a pipeline (similar to the option to create `launch.json`).
4. If they choose not to generate a pipeline, any actions to run experiments should execute the file (can it instead run the active cell in a notebook when appropriate?).
5. If they choose to generate a pipeline, we know the source code file. If we can determine the DVCLive output directory, we could pre-fill dvc.yaml with something like:
```yaml
stages:
  train:
    cmd: python source_file.py
    deps:
      - source_file.py
    outs:
      - dvclive:
          cache: false
```

------

Summary of the discussion during the product sync with @dberenbaum :

- Next step for the onboarding is to focus on "launch configurations" (helping creating a dvc.yaml e.g. when user clicks on a run button)
- We can show a + Pipeline config on the experiments side panel
- On the DVCLive snippets screen we don't show anything extra yet. Eventually we can show alternatives for other languages.

------
- [x] Add a quick pick to prompt the user for their training script to add to the `dvc.yaml` file being created
- [x] Remove beaker button to show experiments and replace with the play button to run experiment (like it is currently is when showing the table)
- [x] If there is a `dvc.yaml` file, also check for a pipeline in the file (check for stages key or run `dvc stage list`)
- [x] Add a mention in the last onboarding step ("Your project contains no data") to tell the user to run their training script after adding DVCLive. (Should be common sense to work with the extension, but not so much if expecting the setup pages to show something in between those steps - "I've added DVCLive, now what?")
- [ ] Add a button below the table if there is no `dvc.yaml` file ("Add configuration")
- [x] Either replace the "Show Experiments" button with "Run Experiment" when the table is open or replace the "Show Experiments and Plots" button with it at all times
- [x] Accept other training scripts (not just python)

**Comment by shcheklein** [comment]
@dberenbaum I think we pretty much do the same now. Except we don't ask for a file to run (what if there is no file yet?). If project is not initialized, DVC is not installed we guide now you thought the steps on a separate screen.

Pipelines is the next stage for us. It can be on the same Setup screen that we have, but also Run button should be generating it, etc - that where we'll indeed start asking about files potentially (what is they are nor Python though?)

If we forget about pipelines for now, do you feel we should move DVCLive snippet from a separate screen (that now also helps with with DVC install, Git install, project init, etc) into something like Quick Pick + code snippets? Or it's fine that we keep it copy-pastable on a screen?

**Comment by dberenbaum** [comment]
> Pipelines is the next stage for us. It can be on the same Setup screen that we have, but also Run button should be generating it, etc - that where we'll indeed start asking about files potentially (what is they are nor Python though?)

💯 Putting this first to clarify that it's related/about this. We should guide users to run experiments by either adding a `dvc.yaml` pipeline or executing a single file, similar to how VS Code encourages adding `launch.json` but also allows debugging with auto config:

<img width="1010" alt="Screenshot 2023-01-09 at 12 19 06 PM" src="https://user-images.githubusercontent.com/2308172/211368343-ebcc4fc8-58b0-437d-8dba-303f4d8a8230.png">

Maybe the proposal was not that clear. We can have further discussion or a call if it's still unclear. I think it's similar to your ideas for pipelines already, with the addition of being able to run experiments without a pipeline (which could be added after the pipelines setup is implemented).

> If project is not initialized, DVC is not installed we guide now you thought the steps on a separate screen.

👍  The workflow to initialize a DVC repo there looks good now IMO thanks to the recent onboarding improvements. This proposal would be what you see after you initialize. 

> I think we pretty much do the same now.

Once I initialize DVC in a project, here's what I see:

<img width="230" alt="Screenshot 2023-01-09 at 12 23 19 PM" src="https://user-images.githubusercontent.com/2308172/211369096-a0f03824-8e82-432f-b65c-45959866a207.png">

If I click on one of the blue buttons, I see this:

<img width="646" alt="Screenshot 2023-01-09 at 12 14 30 PM" src="https://user-images.githubusercontent.com/2308172/211369307-fcf6ad4b-c1fe-400e-946a-d0f772cb097b.png">

Okay, I added that to my file, but I still see this screen. Now what? Right now, the initial sidebar has no visible option to run an experiment, which I might assume is a prerequisite to showing experiments. IMO we should have a prominent action in the sidebar at all times to run experiments.

If you somehow find the option to run experiments, it will try kick off `dvc exp run` despite the pipeline not being set up. Instead, can we detect there is no pipeline? This is where I would introduce the workflow above.

> Except we don't ask for a file to run (what if there is no file yet?). 

Then we need to tell them to create one, right? I don't think we can run experiments without at least some code file.

> what is they are nor Python though?

Right, I had the same question above. IMHO let's see how big the need is before worrying about it - there's no reason we can't run non-Python files, but since DVCLive already pushes towards Python, it makes sense to start with Python.

> If we forget about pipelines for now, do you feel we should move DVCLive snippet from a separate screen (that now also helps with with DVC install, Git install, project init, etc) into something like Quick Pick + code snippets? Or it's fine that we keep it copy-pastable on a screen?

I don't have a strong opinion. IMHO the quick pick/code snippets seem useful once I know what I'm doing and want to make it easier to add DVCLive to my code. I think we need the copy/paste screen to tell people to add it in the first place.

**Comment by dberenbaum** [comment]
@shcheklein If there is somewhere better for these type of product discussions, let me know.

**Comment by shcheklein** [comment]
Summary of the discussion during the product sync with @dberenbaum :

- Next step for the onboarding is to focus on "launch configurations" (helping creating a `dvc.yaml` e.g. when user clicks on a run button)
- We can show a `+ Pipeline config` on the experiments side panel
- On the DVCLive snippets screen we don't show anything extra yet. Eventually we can show alternatives for other languages.

**Comment by dberenbaum** [comment]
> * On the DVCLive snippets screen we don't show anything extra yet. Eventually we can show alternatives for other languages.

We could add some basic language/link to the docs to cover it without too much effort for now. Maybe it's less about other languages and more about providing ways for interested users to get a deeper understanding of what the code snippets are doing and how dvc metrics/plots/params work.

**Comment by mattseddon** [comment]
Related to https://github.com/iterative/vscode-dvc/issues/3021

**Comment by sroy3** [comment]
I’ve been testing the onboarding and thinking about this. We will never see the the experiments table if we haven’t first ran anything. So before even making the distinction between running experiments with or without a configuration file, we need to find a way to show the run button so that it can be run a first time. Like @dberenbaum  was saying, there is no way to run experiments from the extension  after successfully setting up a project. Until then, we’re stuck with the “Your project has no data” screen. My suggestion for this is adding a big blue “Run Experiment” button in the sidebar (probably leave it there at all times). The other solution would be to add the button “Run Experiment” inside of the setup (”Your project has no data” screen). The one con of this second solution is that the user won’t necessarily understand easily how to run other experiments if they depend on this temporary button.

I'll add the button in the sidebar for now (it's practically no effort) so that I can move forward. iIf anything, we can change strategy later.

**Comment by dberenbaum** [comment]
That sounds good, @sroy3. The next step/question is what happens if you don't have a dvc.yaml pipeline and click that run experiment button? Should we suggest they run the script where they added DVCLive themselves? Do we open a pre-filled dvc.yaml pipeline template for them?

**Comment by sroy3** [comment]
> That sounds good, @sroy3. The next step/question is what happens if you don't have a dvc.yaml pipeline and click that run experiment button? Should we suggest they run the script where they added DVCLive themselves? Do we open a pre-filled dvc.yaml pipeline template for them?

Currently on a spike / POC to create a dvc.yaml file

**Comment by sroy3** [comment]
Adding an empty `dvc.yaml` file (as a first step) to the project https://github.com/iterative/dvc-get-started-cv/tree/1-notebook-dvclive makes it able to run experiment and add a new experiment to the experiments table. It works for this project because it is already set up correctly, but it seems that a new project would need more than that to show a table. Adding a `params.yaml` file creates the appropriate columns.

Currently, the last onboarding step is the screen that says "Your project contains no data". From there, we suggest that the user add DVCLive to their project. Should we ask them to create a `params.yaml` file as well? Are there other missing files that are required? 

I'm not certain how a project should look before adding DVCLive to it.

**Comment by sroy3** [comment]
# Summarizing yesterday's meeting

## Tasks

- [ ] Add a quick pick to prompt the user for their training script to add to the `dvc.yaml` file being created
- [ ] Remove beaker button to show experiments and replace with the play button to run experiment (like it is currently is when showing the table)
- [ ] If there is a `dvc.yaml` file, also check for a pipeline in the file (check for stages key or run `dvc stage list`)
- [ ] Add a mention in the last onboarding step ("Your project contains no data") to tell the user to run their training script after adding DVCLive. (Should be common sense to work with the extension, but not so much if expecting the setup pages to show something in between those steps - "I've added DVCLive, now what?")

### Other possible tasks

- [ ] Add a button below the table if there is no `dvc.yaml` file ("Add configuration")
- [ ] Either replace the "Show Experiments" button with "Run Experiment" when the table is open or replace the "Show Experiments and Plots" button with it at all times

## Specifications and clarifications

These might have been obvious for most people, but here are things I learned from the meeting that is helpful to me:

- Running the training script should populate the table on its own (no need to use the run experiment button)
- No `params.yaml` file should be necessary
- `dvc stage list` will show pipelines if any

**Comment by dberenbaum** [comment]
> * If there is a `dvc.yaml` file, also check for a pipeline in the file (check for stages key or run `dvc stage list`)

I would suggest `dvc stage list -R .`. This should be the most robust way to check for stages throughout the project.

**Comment by shcheklein** [comment]
@sroy3 perfect summary, thanks for making it (I really really appreciate it, it's super important for us to be aligned). Please, feel free also to pull the list of items (tasks) to the description and maintain it there. If needed we can split even into smaller tickets.

**Comment by mattseddon** [comment]
>  Remove beaker button to show experiments and replace with the play button to run experiment (like it is currently is when showing the table)

Whilst doing this can we remove all of the `view/title` entries for `dvc.showExperiments` & `dvc.showPlots`? IMO it doesn't make sense to duplicate them with the massive buttons available above.

**Comment by sroy3** [comment]
> > * If there is a `dvc.yaml` file, also check for a pipeline in the file (check for stages key or run `dvc stage list`)
> 
> I would suggest `dvc stage list -R .`. This should be the most robust way to check for stages throughout the project.

Maybe it's something that's not being done on our side, but pipelines in nested `dvc.yaml` files aren't being run in the extension.

**Comment by sroy3** [comment]
To follow-up #3197:

To run a notebook instead of a python script, I found that you can convert and execute a notebook with the following command `jupyter nbconvert --to ANY_NAME --inplace --execute SCRIPT_PATH.ipynb`. This works pretty well. The only downside is that `jupyter` needs to be explicitly installed. 

We might also want to customize the first stage a little more. I'd add a first step to name the stage of the pipeline with a default value of "train". Then instead of the "Enter the path to your training script or select it" step, we could simply ask "Enter the full command to run, or select  a python script or a Jupyter notebook to run". This way, I think we would cover most basic cases. Should we also ask for other files (dependencies, outputs...) or simply invite them to edit the dvc.yaml file to suit their needs?

**Comment by sroy3** [comment]
> We might also want to customize the first stage a little more. I'd add a first step to name the stage of the pipeline with a default value of "train". Then instead of the "Enter the path to your training script or select it" step, we could simply ask "Enter the full command to run, or select a python script or a Jupyter notebook to run". This way, I think we would cover most basic cases. Should we also ask for other files (dependencies, outputs...) or simply invite them to edit the dvc.yaml file to suit their needs?

Concerning this, and mainly running a non-Python command. Are we talking about scripts in other languages or more complex bash commands? For other languages, we could probably have some sort of mapping script extension to command that would make this easier for us. If we are talking about more complex commands (`python script1.py && python scripts2.py`), how  often are we expected to encounter this? Should we simply allow one script and automatically open the `dvc.yaml` file with the newly created pipeline with a comment to pipeline documentation so that they add other stages and customize them to their liking?

**Comment by shcheklein** [comment]
> Should we also ask for other files (dependencies, outputs...) or simply invite them to edit the dvc.yaml file to suit their needs?

We can add a dep on the script file (e.g. `train.py`).
We can add additional fields commented out to show more option + a link to the docs.

> Are we talking about scripts in other languages or more complex bash commands? 

I would not bother too much with this, notebook and Python are enough. Everything else - I would put them into `cmd` as-is.

> We might also want to customize the first stage a little more. I'd add a first step to name the stage of the pipeline with a default value of "train"

Yep, sounds good! All the suggestions are reasonable.

**Comment by sroy3** [comment]
For the add configuration button. Here are two placement possibilities:

**A (bottom right corner)**

https://user-images.githubusercontent.com/3683420/218545777-1a5d29bd-4fc7-4772-b526-5dde6e9f35f7.mov

**B (bottom of table)**

https://user-images.githubusercontent.com/3683420/218546180-1ca5f23f-b0a9-4e95-ab75-0332c3219c39.mov

Let me know which would be preferred.

**Comment by shcheklein** [comment]
@sroy3 let's make bottom of the table. I also think it's fine for the button to be hidden if table is big enough (no need for it to float on top of the table).

- We should disable this if there is already a `dvc.yaml` with stages
- Can we make it a link not a button?
- We can then include some text (in dark grey, similar to the onboarding screen or to the VS Code empty screen if close alls tabs) - "Add a project file for reproducibility, for queueing and running experiments in parallel. "

wdyt?

**Comment by sroy3** [comment]
> * We should disable this if there is already a `dvc.yaml` with stages

Already implemented (still only in local version)

> * Can we make it a link not a button?

A button seems like a better choice for what it is supposed to do. It's an action. Links are for linking. We expect to be redirected when clicking. Clicking "Add a configuration" will simply pop the same implemented steps to create a basic pipeline. Unless we want to create a different process (create a `dvc.yaml` file with a template where the user fills everything on their own?). If we really want to go with a link, I'll do it, but IMO a button suits the purpose better.

> * We can then include some text (in dark grey, similar to the onboarding screen or to the VS Code empty screen if close alls tabs) - "Add a project file for reproducibility, for queueing and running experiments in parallel. "

That's possible. I'll do that one in a second step to keep the PR context light.

**Comment by dberenbaum** [comment]
Looks good @sroy3! 

@shcheklein As a follow up, what do you think of making it so that all the `run`/`queue` actions (like the play button at the top of the table) redirect to `add configuration` if there's no existing stages? This will also help users understand the benefits of adding it, along with hints in the file itself.

**Comment by shcheklein** [comment]
>  As a follow up, what do you think of making it so that all the run/queue actions (like the play button at the top of the table) redirect to add configuration if there's no existing stages? This will also help users understand the benefits of adding it, along with hints in the file itself.

Yes, definitely. They all should behave the same way.
