### ISSUE TITLE
Review: DVC-tracked files intergration

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#330]
Review placeholder for the https://github.com/iterative/vscode-dvc/issues/207 . I'll keep updating it. Feel free to create specific tickets/PR to address items here (refer to comments).

- [x] In the SCM tree we don't want to show changes that correspond to the pipeline dependencies. Also, we can't assign actions (push/pull) to them - https://github.com/iterative/vscode-dvc/issues/330#issuecomment-827317109
- [x] Manage (e.g. `pull`) DVC-tracked directories from the SCM view as a whole https://github.com/iterative/vscode-dvc/issues/330#issuecomment-827318034
- [x] Performance: `dvc list` keeps running itself ~https://github.com/iterative/vscode-dvc/issues/330#issuecomment-827326600~ https://github.com/iterative/vscode-dvc/issues/330#issuecomment-831648927
- [x] Experiments commands in the SCM dropdown is not very relevant - https://github.com/iterative/vscode-dvc/issues/330#issuecomment-827340817
- [x] Extending file watcher for updates to views - [This comment](https://github.com/iterative/vscode-dvc/pull/351#issuecomment-829619277)
- [x] Unrelated files in the SCM views (not tracked by DVC or Git) - https://github.com/iterative/vscode-dvc/issues/330#issuecomment-831649481
- [x] Different icons for directories in the SCM tree https://github.com/iterative/vscode-dvc/issues/330#issuecomment-835912970
- [x] Do not show DVC trees in non DVC repos https://github.com/iterative/vscode-dvc/issues/330#issuecomment-835913995
- [x] Add push / pull to explorer tree https://github.com/iterative/vscode-dvc/issues/318#issuecomment-837607977
- [x] Remove push / pull from inline SCM and add to repository level https://github.com/iterative/vscode-dvc/issues/318#issuecomment-837607977
- [x] Change trees logic after the discussion in the https://github.com/iterative/vscode-dvc/issues/318 , example is here https://github.com/iterative/vscode-dvc/issues/330#issuecomment-842865096
- [x] Adding data SCM tree view behavior is not clear - https://github.com/iterative/vscode-dvc/issues/330#issuecomment-843580760
- [x] If we move to `diff`: Duplicate entries when file is tracked by git (incorrectly or not) - https://github.com/iterative/vscode-dvc/issues/330#issuecomment-844739515 (raise DVC issue?)
- [x] Modified is not presented correctly? https://github.com/iterative/vscode-dvc/issues/330#issuecomment-848217287
- [x] General performance- https://github.com/iterative/vscode-dvc/issues/330#issuecomment-827341763
- [x] In the DVC Tracked Tree we should be showing progress for pull/push https://github.com/iterative/vscode-dvc/issues/330#issuecomment-843536818
- [x] #609
- [x] Failed fast instead of force flags https://github.com/iterative/vscode-dvc/issues/330#issuecomment-851734478
- [x] Binary file open action error message behavior https://github.com/iterative/vscode-dvc/issues/330#issuecomment-851755392
- [x] Do not grey out DVC-tracked files/directories. Use it for "still in cache"/missing?  https://github.com/iterative/vscode-dvc/issues/330#issuecomment-851756898
- [x] Deleting files in the dataset should make it modified - https://github.com/iterative/vscode-dvc/issues/330#issuecomment-851762235
- [x] Glitch with tracking state on the file system - https://github.com/iterative/vscode-dvc/issues/330#issuecomment-851763528
- [x] Implement regular file operations on trees. Probably worth creating a separate ticket - https://github.com/iterative/vscode-dvc/issues/330#issuecomment-857162792
- [x] Decide on whether to extend force flag behaviour to push, pull, remove in the tracked explorer tree.
- [x] Improve messaging for failed commands that may be fixed by use of force flags - https://github.com/iterative/vscode-dvc/pull/548#issuecomment-861038791
