### ISSUE TITLE
Improve Custom Plots

### ISSUE THREAD

**Issue by julieg18** [iterative/vscode-dvc#3373]
Tasks are sorted by importance. 

```[tasklist]
### Tasks
- [x] Remove Trends section, instead having trends plots be plots you can create in "Custom". This will simplify the code logic and duplication.
- [x] Update README/Walkthrough
- [x] Remove the possibility of a user selecting options that create a plot that is already made. Currently an error popup will appear if a user does this. (See [#3342 discussion](https://github.com/iterative/vscode-dvc/pull/3342#discussion_r1120171539))
- [x] Add commit data into custom plots
- [x] Update get started screen (see https://github.com/iterative/vscode-dvc/pull/3382#discussion_r1125568446)
- [x] Add command pallete commands
- [x] Have metric vs param plots use scatter plots instead of linear plots
- [x] Make sure that custom spec does not generate errors in `webview/src/plots/components/App.test.tsx` (https://github.com/iterative/vscode-dvc/pull/3575#discussion_r1155414065)
- [x] [Delete old Persistance metrics state](https://github.com/iterative/vscode-dvc/pull/3404#discussion_r1133350817) (#3518)
- [x] [Adjust custom plots order state](https://github.com/iterative/vscode-dvc/pull/3404#discussion_r1133350999) (#3518)
- [x] Investigate loading section test (https://github.com/iterative/vscode-dvc/pull/3404#discussion_r1133370484)
- [x] Update walkthrough images after other PRs are merged (https://github.com/iterative/vscode-dvc/pull/3404/files#r1133343393)
- [x] Check if plot spec creation can be moved to extension (https://github.com/iterative/vscode-dvc/pull/3404#discussion_r1134686640)
- [x] Consolidate type checking to the smallest space/amount of functions (https://github.com/iterative/vscode-dvc/pull/3404#discussion_r1134686640) (Most of this has been done already but more to do)
- [x] Add code to add 1 trend and 1 metric vs param custom plot to e2e test (https://github.com/iterative/vscode-dvc/pull/3404/files#r1133364032)
- [x] Improve Jest testing on plots section (see [#3342 comment](https://github.com/iterative/vscode-dvc/pull/3342#discussion_r1120188485))
```

Followup to #3342

**Comment by mattseddon** [comment]
Addition of a custom plot with no experiments present breaks the empty state screen:


https://user-images.githubusercontent.com/37993418/222307123-a8adab15-0109-4698-8520-3afba4c4fec4.mov

**Comment by mattseddon** [comment]
Lower priority but we should change "iteration" to step and make it 0 based (same as DVCLive) for the checkpoint trends plots:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/223601412-6675ad90-83ce-4c48-855d-bc12cf92ae4f.png">

**Comment by julieg18** [comment]
> Add commit data into custom plots

@mattseddon, what do you mean by commit data? I know we have rows that we refer to as `commits` but custom plots rely on experiments 🤔

**Comment by mattseddon** [comment]
> > Add commit data into custom plots
> 
> @mattseddon, what do you mean by commit data? I know we have rows that we refer to as `commits` but custom plots rely on experiments 🤔

Regarding custom plots (not trends) commits and experiments contain the same data. Is there a reason to exclude the baselines (commits) from custom plots?

**Comment by shcheklein** [comment]
Sounds reasonable to me @dberenbaum , thanks for the feedback!

**Comment by daavoo** [comment]
> I think we should use something like the smooth template we have for other plots, where we show the points but generate a smoothed line:

I think we should not show a line at all, and use pure scatter plot template, like:

https://vega.github.io/vega-lite/examples/point_color_with_shape.html

**Comment by dberenbaum** [comment]
@daavoo I thought it might be helpful to have a trend line since it could be noisy with many experments, and a typical use case is to try to see a rough pattern of how the metric varies with changes to the hyperparameter. Any reason you prefer not to show a line at all?

To clarify, unlike the screenshot I included above, I would only expect a single line on these plots.

**Comment by daavoo** [comment]
> I thought it might be helpful to have a trend line since it could be noisy with many experments, and a typical use case is to try to see a rough pattern of how the metric varies with changes to the hyperparameter.

That sounds like parallel coordinates 😅 

> Any reason you prefer not to show a line at all?

No strong reason. Just don't try to do too much in one type of plot.

It just feels cleaner / aligned with existing tools, at least as default (wandb does allow to  _optionally_ insert line into scatter plot, but it also provides different options on how to add the line).

**Comment by dberenbaum** [comment]
Okay, I don't see it as a blocker, so I'm fine to go with a scatter plot for now. We could always add either a loess or linear regression line later and have an option to show/hide it.

**Comment by julieg18** [comment]
Tried three different plots:

1. A smooth plot based off our dvc templates
2. scatter plot
3. scatter plot with a regression line

The smooth plot seemed kind of buggy though I'm not sure if it's due to the experiment values or me configuring the plot incorrectly. Scatter plots seem simple enough to create though:


https://user-images.githubusercontent.com/43496356/229650431-91bde69b-4691-4114-8190-9c3a5c6cc013.mov

https://user-images.githubusercontent.com/43496356/229650789-d1f98a47-96dd-4b65-90cb-dc07b4367330.mov

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/43496356/229650901-d130f1ff-699a-43c3-a519-f1c89f0f6df2.png">

What do we think will work best? cc @iterative/vs-code, @shcheklein
