### ISSUE TITLE
Review: Experiments workflow

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#374]
Review placeholder for the #239 

- [x] Very slow run, depends on the DVC improvement here - https://github.com/iterative/dvc/issues/5638
- [x] When I run an experiment I want to see in the table immediately (to be able to stop, etc) https://github.com/iterative/dvc/issues/5965
- [x] Terminal that disappears is suboptimal from UX perspective. Can we capture the whole output and save it? Can we reuse the regular terminal?
- [ ] Try to debug an experiment (break point) - @shcheklein 
- [x] Updates to workspace are not visible https://github.com/iterative/vscode-dvc/issues/374#issuecomment-835874408
