### ISSUE TITLE
Improve DVC Setup "DVC is Unavailable" step

### ISSUE THREAD

**Issue by julieg18** [iterative/vscode-dvc#3935]
Currently, vscode-dvc will see if the python extension has a python environment selected, then offer to install DVC and DVCLive inside said environment with `pip`. There are couple things to possibly improve with this:

![image](https://github.com/iterative/vscode-dvc/assets/43496356/b9017f6d-e858-48e7-a902-5d3a229a17c3)

* The python extension will tend to select a global environment by default if there is no virtual env. Installing DVC there is most likely unwanted and even dangerous. 
*  Some users aren't using `pip` to install their packages.
* It's unclear that we are finding the environment using the python extension

Related comments: https://github.com/iterative/vscode-dvc/issues/3434#issuecomment-1544772389, https://github.com/iterative/vscode-dvc/issues/3434#issuecomment-1544775451, https://github.com/iterative/vscode-dvc/pull/3904#discussion_r1197163784

### Task List

- [x] Change our "Install" button to "Install (pip)". (A quick way to clear things up a little more for now)
- [x] Research the possibility of recognizing that the user is not in a virtual environment and/or creating a virtual environment for them (look at Jupyter extension)
- [x] Research how we can install packages other than pip  
- [x] ~Use different install commands based on user's environment~ (no longer needed for now)
- [x] Incorporate the Python Extension's Create Env... into the setup. (We could add an extra quick pick in our Configure command that adds the Create Env option OR show an extra button in the Setup page)
- [x] Rethink step contents, and review what we can adjust to make DVC configuration more clear (Main points to review: Configure button name, information on how we got selected environment, and adding a "Select Python Interpreter" button)

**Comment by julieg18** [comment]
>  Research the possibility of recognizing that the user is not in a virtual environment and/or creating a virtual environment for them (look at Jupyter extension)

Looks like we do both of these things with help from the Python Extension! We can find out if a user is using a virtual environment with the extension's API (specifically their `environments` utils) and we can run the `Python: Create Environment...` command to create a new environment.

**Comment by julieg18** [comment]
>  Research how we can install packages other than pip

Looking at Jupyter, they are running commands, decided on args based off the environment information given by the Python Extension. `conda install PACKAGE_NAME --name NAME` for a named conda environment, `pip install -U PACKAGE_NAME` for a python venv, etc. We can probably do something similar to install DVC and DVCLive instead of just using pip for any environment like we currently are. 

With issue research done, I'll start testing some of these ideas and post some design possibilities next!

**Comment by julieg18** [comment]
## Current Plan

>  Use different install commands based on user's environment

Going to start off with this task so that the "Install" button will be useable for users that aren't using `pip`. Once it's done, we'd only have to default to pip if the user has an unknown env. It also doesn't need any design work since it's just adjusting the commands we run internally and removing the Setup `pip` mentions for users with known environment types. 

## Design Ideas

> Recognize that the selected python environment is not a virtual environment and prompt them to create a virtual environment

One idea I had was show a "Create Env" button if the user is in a global env. This "Create Env" would run the "Python: Create Environment..." then install DVC packages within that environment. Could also remove the "Install" button entirely if the user is in a global environment if there isn't a use case where you're going to want DVC installed in a global python environment.

<img width="745" alt="Screenshot 2023-06-05 at 4 33 40 PM" src="https://github.com/iterative/vscode-dvc/assets/43496356/626a0ac3-e1e7-47b7-9761-050a41114773">

****

> Improve the step contents, giving the user a better understanding of the selected environment

Sounds like something we could put in the DVC CLI details. An example of adding an "Environment" row: 

<img width="717" alt="Screenshot 2023-06-05 at 4 58 55 PM" src="https://github.com/iterative/vscode-dvc/assets/43496356/7e9cecee-9d6a-4377-aca6-835dfb93b0f7">
<img width="643" alt="Screenshot 2023-06-05 at 5 04 24 PM" src="https://github.com/iterative/vscode-dvc/assets/43496356/8be6e36e-fd33-4c09-be4c-766c3b68029c">

Another option is adjusting our text content, but it felt verbose when I attempted that:

<img width="680" alt="Screenshot 2023-06-05 at 5 08 52 PM" src="https://github.com/iterative/vscode-dvc/assets/43496356/bb01db14-cb32-427d-9ff9-554e2750f2a1">

What do we think? Any other ideas? cc @iterative/vs-code, @shcheklein

**Comment by julieg18** [comment]
After the discussion in the planning meeting, going to update the task list: 

### **Old task list**

- [ ] Use different install commands based on user's environment
- [ ] Recognize that the selected python environment is not a virtual environment and prompt them to create a virtual environment
- [ ] Improve the step contents, giving the user a better understanding of the selected environment

For now, we're going to just focus on using `pip` for an install command since:
* it's used in many cases
* there is no vscode command we can run to get a desired install command, we'd have to create desired commands from scratch, meaning more code to maintain 

### New Task List

- [ ] Incorporate the Python Extension's `Create Env...` into the setup. (We could add an extra quick pick in our `Configure` command that adds the `Create Env` option OR show an extra button in the Setup page)
- [ ] Rethink step contents, and review what we can adjust to make DVC configuration more clear (Main points to review: `Configure` button name,  information on how we got selected environment, and adding a "Select Python Interpreter" button)

**Comment by shcheklein** [comment]
@julieg18 thanks! let me know if you need to review the text or iterate on it.

**Comment by julieg18** [comment]
Created some ideas for improving the step contents:

### Old Design

<img width="744" alt="Screenshot 2023-06-10 at 6 20 12 PM" src="https://github.com/iterative/vscode-dvc/assets/43496356/c329738a-83d4-4f10-a50b-f1d32bbad294">

### New Design 

<img width="764" alt="Screenshot 2023-06-10 at 6 15 09 PM" src="https://github.com/iterative/vscode-dvc/assets/43496356/d3a1e286-46de-4ecb-8664-c3705fca3be0">

* adds a warning text in parenthesis if the environment is not a virtual one
* adds a button that opens a quick pick, letting the user choose between creating an environment or selecting from current ones
* renames "Configure" to "Locate DVC"

I also thought of simplifying the "Create or Set Env" button, but wasn't sure if "Set Env" was clear enough: 

<img width="754" alt="Screenshot 2023-06-10 at 6 12 22 PM" src="https://github.com/iterative/vscode-dvc/assets/43496356/6e7e74bf-5864-402a-b747-ffa5f90ab3b2">

Another idea was putting more focus on the python extension actions and moving the "setup the workspace" command into the text:

<img width="727" alt="Screenshot 2023-06-10 at 6 14 37 PM" src="https://github.com/iterative/vscode-dvc/assets/43496356/ddfad8c4-49fd-4a42-83fc-e36688c0f2e7">

I'll get started on the first image for now. What do we think? cc @shcheklein

**Comment by mattseddon** [comment]
I think we can remove the second sentence from the new design:

![image](https://github.com/iterative/vscode-dvc/assets/37993418/b3a74ce4-2e77-4a9d-be39-13759aa5fd76)

If needed put `(pip)` after `Auto-install` or somewhere in the final sentence but I think it can be skipped.
