### ISSUE TITLE
Simplify Webview Architecture

### ISSUE THREAD

**Issue by rogermparent** [iterative/vscode-dvc#397]
After the new designs, all that remains in the table Webview is displaying the Experiments as a table:

![New table design](https://user-images.githubusercontent.com/9111807/117482485-7456c000-af32-11eb-9b53-61666a4595d7.png)

This, along with a shift toward native UI elements like TreeViews, means we need to move a lot of the webview logic into the extension and, ideally, not duplicate work within the Webview. Since the webview handles a _lot_ right now, it's best to break this into steps

## Tasks

From a high level, one can consider refactoring out the columns a task that can be handled separately from moving over the experiments themselves. From there, both tasks can be broken up into a sequence of smaller tasks.

Columns can be fully reimplemented can before starting on experiments, and doing to will allow us to work on both refactoring the Webview and building on the Columns data in parallel.

- [x] **Columns**
  - [x] Parse and expose the column schema in Extension (#358)
  - [x] DRY-ly use the extension-parsed columns in the Webview table
  - [x] Add native UI elements for column control (#359 #362 #363), which can be usable pre-experiments by puppeting `react-table`'s filter/sort/hide state
  - [x] Remove Webview columns UI

- [x] **Experiments**
  - [x] Parse experiments (turn the object into an array, organize `baseline`s and `checkpoint_tip`s into the hierarchy they represent) in the extension
  - [x] Sort experiments in the extension
  - [x] Filter experiments in the extension
  - [x] Remove sort/filter logic from Webview and consume from Extension
  - [x] Make a native UI to keep track of experiments at a glance

## Other considerations:

- We could explore using command URI links instead of JS-based message passing
- With so much less responsibility, we can use a much lighter and simpler state solution for the webview, like `useReducer`
